export {default as welcome } from './main/welcome.png'
export {default as whatis } from './page2/whatiszcash.png'
export {default as introduction } from './page3/Introduction.png'
export {default as zkp } from './page4/zkp.png'
export {default as Shielded } from './page5/ShieldedPools.png'
export {default as ecosystem } from './page6/ecosystem.png'
export {default as payments } from './page7/payments.png'
export {default as createWallet } from './page8/createawallet.png'
export {default as appWallet } from './page9/App-walleaddresses.png'
export {default as MemoTesting } from './page10/10 Memo Testing.png'
export {default as explore } from './page11/11 Explore.png'
export {default as eduzecLogo } from './EduZECLogo.webp'