export {default as welcome } from './main/welcome.png'
export {default as whatis } from './page2/whatiszcash.png'
export {default as gifGuy } from './page2/gifGuy.gif'
export {default as backgroundWhat} from './page2/What_is_Zcash_background.webp'
export {default as introduction } from './page3/Introduction.png'
export {default as introBkg} from './page3/Introduction_background.webp'
export {default as zkp } from './page4/zkp.png'
export {default as zkpBackground } from './page4/Zero_Knowledge_Proofs_background.webp'
export {default as Shielded } from './page5/ShieldedPools.png'
export {default as shieldedTree} from './page5/tree.webp'
export {default as shieldedBkg} from './page5/shieldedBkg.png'
export {default as ecosystem } from './page6/ecosystem.png'
export {default as freeZ } from './page6/Ecosystem_FreeZ.webp'
export {default as zecPages } from './page6/Ecosystem_zecPages.webp'
export {default as zecHub } from './page6/Ecosystem_zechub.webp'
export {default as zkRadio } from './page6/Ecosystem_zkRadio.webp'
export {default as zkav } from './page6/Ecosystem_zkav.webp'
export {default as appWallet } from './page9/App-walleaddresses.png'
export {default as MemoTesting } from './page10/10 Memo Testing.png'
export {default as payments } from './page7/payments.png'
export {default as zpayments } from './page7/zpayments.webp'
export {default as coinsbee } from './page7/coinsbee.webp'
export {default as flexa } from './page7/flexa.webp'
export {default as zgo } from './page7/zgo.webp'
export {default as createWallet } from './page8/createawallet.png'
export {default as createGuy } from './page8/createGuy.gif'
export {default as dash } from './page8/dash.gif'
export {default as ezcash } from './page8/ezcash.gif'
export {default as unstopa } from './page8/unstopa.gif'
export {default as ywallet } from './page8/ywallet.gif'
export {default as zashi } from './page8/zashi.gif'
export {default as zingo } from './page8/zingo.gif'
export {default as explore } from './page11/Explore.png'
export {default as exploreGuy } from './page11/exploreGuy.gif'
export {default as eduzecLogo } from './EduZECLogo.webp'